"""add City model

Revision ID: 170a479a518b
Revises: 8354bb4fbbff
Create Date: 2024-04-10 00:59:38.474126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '170a479a518b'
down_revision: Union[str, None] = '8354bb4fbbff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False), schema='catalog')
    op.add_column('company_branch', sa.Column('is_active', sa.Boolean(), nullable=False), schema='catalog')
    op.drop_column('company_branch', 'city_id', schema='catalog')
    op.drop_column('company_branch', 'timezone', schema='catalog')
    op.drop_column('profiles', 'city_id', schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False), schema='catalog')
    op.add_column('company_branch', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True), schema='catalog')
    op.add_column('company_branch', sa.Column('city_id', sa.UUID(), autoincrement=False, nullable=False), schema='catalog')
    op.drop_column('company_branch', 'is_active', schema='catalog')
    op.drop_column('companies', 'is_active', schema='catalog')
    # ### end Alembic commands ###
