"""init partitions

Revision ID: 8354bb4fbbff
Revises: e7b11896ad60
Create Date: 2024-03-31 20:06:23.646458

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from src.core.config import settings

# revision identifiers, used by Alembic.
revision: str = "8354bb4fbbff"
down_revision: Union[str, None] = "e7b11896ad60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"CREATE TABLE IF NOT EXISTS {settings.db.db_schema}.user_sign_in_api \
        PARTITION OF {settings.db.db_schema}.users_sign_in FOR VALUES IN ('api')"
    )
    op.execute(
        f"CREATE TABLE IF NOT EXISTS {settings.db.db_schema}.user_sign_in_mobile \
        PARTITION OF {settings.db.db_schema}.users_sign_in FOR VALUES IN ('mobile')"
    )
    op.execute(
        f"CREATE TABLE IF NOT EXISTS {settings.db.db_schema}.user_sign_in_web \
        PARTITION OF {settings.db.db_schema}.users_sign_in FOR VALUES IN ('web')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP TABLE IF EXISTS {settings.db.db_schema}.user_sign_in_api")
    op.execute(f"DROP TABLE IF EXISTS {settings.db.db_schema}.user_sign_in_mobile")
    op.execute(f"DROP TABLE IF EXISTS {settings.db.db_schema}.user_sign_in_web")
    # ### end Alembic commands ###
